name: Build PDF
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Sets the working directory
      # This runs the following commands on an environment with texlive-full.
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            english.typ

      # Move the generated pdf to a folder and deploy that folder to branch 'pdf'.
      - run: mkdir pdf
      - run: mv -t pdf/ english.pdf
      - name: Deploy to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pdf
          FOLDER: pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
