name: Build PDF
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Sets the working directory

      # Set config from secrets, download and run Typst compiler
      - name: Set variables from secrets
        env:
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          echo "phone = $PHONE_NUMBER" >> conf.toml
          echo "email = $EMAIL" >> conf.toml
          echo "redact = true" >> conf.toml

      - name: Download Typst and compile
        run: |
          wget https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xf typst-x86_64-unknown-linux-musl.tar.xz
          typst-x86_64-unknown-linux-musl/typst compile --font-path=fonts/ english.typ

      # Move the generated pdf to a folder and deploy that folder to branch 'pdf'.
      - run: mkdir pdf
      - run: mv -t pdf/ english.pdf
      - name: Deploy to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pdf
          FOLDER: pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
